# AWS accounts configs
accounts:
  # AWS Account config id
  dev-team:
    # Account name
    name: system Dev/Stg
    # Excluding Instance config
    exclusions:
      - j-06cebed121c9ehoge
    # ID of Slack notification destination setting
    sender: dev-team
    # AWS credential profile that you use
    profile: default
    region: ap-northeast-1

# Sender configs
senders:
  # Slack notification destination configs
  slacks:
    # Sender config id
    dev-team:
      channel: production_notifications
      username: Notifier
      icon_emoji: smirk
      web_hook: https://hooks.slack.com/hoge/foo

    personal:
      channel: aws_notifications
      username: Notifier
      icon_emoji: smile
      web_hook: https://hooks.slack.com/hoge/foo
