accounts:
  personal:
    sender: test
#    credential_profile: default

senders:
  slack:
    test:
      channel: 51_tech_blog
      username: "Code Review Notifier"
      icon_emoji: dog
      user_map:
        - yurisan:hirachan
      web_hook: https://hooks.slack.com/services/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
